name: Test Voltello
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Call the API
        run: |
          curl -s -i \
            -H "apiKey: ${{ secrets.VE_KEY }}" \
            "https://acapi.vecddevau1.village.energy/xv1/get/customer/energy/electricity/servicepoints/Voltello/CUSTOMERS/Individual/${{ secrets.VE_CUSTOMER }}"
